# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: traits
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=2.7
  - bitarray=0.8
  - nose=1.3
  - pybedtools=0.7
  - pip
  - pip:
    - scipy==0.18
    - pandas==0.20
    - numpy==1.16
  - r-base
  - r-irkernel
  - r-devtools
  - r-kableextra
  - r-htmltools
  - cairo
  - fonts-anaconda=1
  - r-data.table
  - r-tidyverse
  - conda-forge::r-optparse